---
  - hosts: project
    become: yes
    tasks:
      - ufw:
         rule: "allow"
         port: "{{ item }}"
         proto: "tcp"
        with_items:
          - "22"
          - "80"
          - "443"
